import 'dart:ui';

class AppColor {
  static final blue = const Color(0xFF0a558e);
  static final lightblue = const Color(0xFFfafafa);
  static final orange = const Color(0xFFff4c01);
  static final white = const Color(0xFFffffff);
  static final voilet = const Color(0xFF7F00FF);
  static final lightwhite = const Color(0xFFe6e5f3);
  static final lightblue2 = const Color(0xFFb6cbdc);
  static final lb2 = const Color(0xFFe6e6ee);
  static final pink = const Color(0xFFf0635a);
  static final lightblack = const Color(0xFF9c9898);
  static final Appbarcolor = const Color(0xFF0FF151026);
  static final lightwhite2 = const Color(0xFFe5e5e5);
  static final darkblue = const Color(0xFF17387b);
  static final lightblack2 = const Color(0xFF282828);
  static final Gray = const Color(0xFFbebebe);
  static final Orange = const Color(0xFFffad4e);
  static const transparentBlue = const Color(0xFF112b5c);
  static const figmalightblack = const Color(0xFF070821);
  static const figmabutton = const Color(0xFF4552CB);
  static const figmadevider = const Color(0xFFBBC3CE);
  static const figmablacktext = const Color(0xFF070821);
  static const figmasignuptext = const Color(0xFF4552CB);
  static const figmastepper = const Color(0xFFF1A852);
  static const figmabackgroundstepper = const Color(0xFFe7e7f7);
  static const figmaScaffoldBG = const Color(0xFFf8f7fc);
  static const figmapetcaretext = const Color(0xFFFFCF6F);
  static const figmavoilet = const Color(0xFF4552CB);
  static const figmagray = const Color(0xFFBBC3CE);
  static const stepper = const Color(0xFFe4e3f3);
  static const lightgray = const Color(0xFFf0f0f8);
  static const lightgray2 = const Color(0xFFF8F7FB);
  static const ratting = const Color(0xFFBBC3CE);
  static const gradient = const Color(0xFF4ce389);
  static const textfieldcolor = const Color(0xFF252525);
  static const logintoyouraccount = const Color(0xFF09051C);
  static const appbartittle = const Color(0xFF47505A);
  static const deawer = const Color(0xFF454545);
  static const searchbar = const Color(0xFFF7F7F7);
  static const recommended = const Color(0xFF647039);
  static const blackteaa = const Color(0xFF47505A);
  static const teawidget = const Color(0xFFEBFFA2);
  static const lemonteatext = const Color(0xFF647039);
  static const willbuy = const Color(0xFF262424);
  static const widget = const Color(0xFF707070);
  static const dollor = const Color(0xFF647039);
  static const bottomnavigationitem = const Color(0xFFACCB39);
  static const purchase = const Color(0xFF000000);
  static const darkgreen = const Color(0xFFA6CE16);
  static const drawer = const Color(0xFF47505A);
  static const drawercolor = const Color(0xFF000000);
  static const lemonpage = const Color(0xFFd7ef7f);
}

